### ISSUE TITLE
使用 CLB 端口池为 Pod 映射公网地址几个疑问

### ISSUE THREAD

**Issue by sunzwy** [tkestack/tke-extend-network-controller#2]
目前我的部署文件如下
```yaml
---
# {{- if .Values.modules.game.useTkeCluster }}
apiVersion: networking.cloud.tencent.com/v1alpha1
kind: CLBPortPool
metadata:
  name: hpw-game-match-test
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}  
spec:
  startPort: 5000 # 端口池中 CLB 起始端口号
  exsistedLoadBalancerIDs: [{{ .Values.modules.game.clbIds }}] # 指定已有的 CLB 实例 ID，可动态追加
  autoCreate:
    enabled: true # 是否启用在 CLB 端口不足时自动创建 CLB
# {{- end }}
---
apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: {{ .Values.modules.game.gameTag }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.modules.game.replicas }}
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 100%
  network:
    networkType: TencentCloud-CLB
    networkConf:
      - name: ClbIds
        value: "{{ .Values.modules.game.clbIds }}"
      - name: PortProtocols
        value: "8080/TCP"
  gameServerTemplate:
    # {{- if .Values.modules.game.useTkeCluster }}
    annotations:
        networking.cloud.tencent.com/enable-clb-port-mapping: "true"
        networking.cloud.tencent.com/clb-port-mapping: "8080 TCP hpw-game-match-test"
    # {{- end }}
    spec:
      serviceAccountName: {{ .Values.modules.gateway.serviceAccountName }}
      containers:
        - name: {{ .Values.modules.game.gameTag }}
          image: "{{ .Values.registry }}{{ .Values.imagePrefix }}/{{ .Values.modules.game.image }}:{{ .Values.modules.game.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.modules.game.websocketPort }}  # 容器内部端口
          env:
            - name: JAVA_OPTS
              value: {{ .Values.modules.game.java_opts }}
            - name: IS_CRI_ENV # 是否标准环境
              value: "{{ .Values.modules.game.isCriEnv }}"
            - name: roomGatewayHost
              value: {{ tpl .Values.modules.game.roomGatewayTemplate . }}
            - name: GS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name:  GS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEFAULT_WEBSOCKET_PORT
              value: "{{ .Values.modules.game.websocketPort }}"
            - name: GS_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          command: ["sh", "-c"]
          args:
            - java $JAVA_OPTS -cp app.jar:lib/* {{ .Values.modules.game.entrance }}
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # {{- if .Values.modules.game.useTkeCluster }}    
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
          # {{- end }}    
      # {{- if .Values.modules.game.useTkeCluster }}
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "clb-port-mapping"
                fieldRef:
                  fieldPath: metadata.annotations['networking.cloud.tencent.com/clb-port-mapping-result']
```
现在出现的问题是 负载均衡的监听器已经创建成功，没有绑定到我的Pod上
请问一下我的配置是哪里出问题了呢
使用的是普通节点。
是否和`使用 CLB 为 Pod 分配公网地址映射`一样需要用原生节点或者超级节点。

负载均衡上的端口起始是否和```spec:startPort:```相关，看到我这边设置的起始时5000，负载那边的起始端口时700

tke 插件镜像为 `imroc/tke-extend-network-controller:2.0.0-beta.0`

在这里发现这些已经生成

![Image](https://github.com/user-attachments/assets/d6cdb32d-2da9-4e4c-905e-ae45fcf1aac6)

**Comment by imroc** [comment]
我看你用的 OKG 的 TencentCloud-CLB 插件，这个依赖的是  tke-extend-network-controller 的旧 API，未来会迁移到新 API（端口池），同时也用了新 API。

旧 API 绑定 pod 用的 CRD 是 dedicatedclblistener，不支持普通节点。旧 API 和新 API 不能同时使用，可以删除 OKG 的这段 network 配置：

```yaml
  network:
    networkType: TencentCloud-CLB
    networkConf:
      - name: ClbIds
        value: "{{ .Values.modules.game.clbIds }}"
      - name: PortProtocols
        value: "8080/TCP"
```

如需技术支持，可加微信

![Image](https://github.com/user-attachments/assets/d700b3b7-8fc9-4427-ac62-376e31ba7864)
